/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\models\adventurtime.glb -t 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Plane_1: THREE.Mesh;
    Plane_2: THREE.Mesh;
    Plane_3: THREE.Mesh;
    Sphere: THREE.Mesh;
    Sphere001: THREE.Mesh;
    Sphere002: THREE.Mesh;
    Sphere003: THREE.Mesh;
    Cube001_1: THREE.Mesh;
    Cube001_2: THREE.Mesh;
    BezierCurve: THREE.Mesh;
    Cube003: THREE.Mesh;
    BezierCurve005_1: THREE.Mesh;
    BezierCurve005_2: THREE.Mesh;
    BezierCurve004: THREE.Mesh;
    Cube009: THREE.Mesh;
    Cylinder_1: THREE.Mesh;
    Cylinder_2: THREE.Mesh;
    Cylinder001: THREE.Mesh;
    Cylinder002: THREE.Mesh;
    BezierCurve005: THREE.Mesh;
    Cylinder004: THREE.Mesh;
    Cylinder007: THREE.Mesh;
    Plane005: THREE.Mesh;
    Plane006: THREE.Mesh;
    Plane007: THREE.Mesh;
    Plane008: THREE.Mesh;
    Cube012: THREE.Mesh;
    Plane009: THREE.Mesh;
    Plane010: THREE.Mesh;
    Cube013_1: THREE.Mesh;
    Cube013_2: THREE.Mesh;
    Plane011: THREE.Mesh;
    Plane012: THREE.Mesh;
    Plane013: THREE.Mesh;
    Plane014: THREE.Mesh;
    Plane015: THREE.Mesh;
    Plane016: THREE.Mesh;
    Plane017: THREE.Mesh;
    Plane018: THREE.Mesh;
    Cube014_1: THREE.Mesh;
    Cube014_2: THREE.Mesh;
    Cube016_1: THREE.Mesh;
    Cube016_2: THREE.Mesh;
    Cube017_1: THREE.Mesh;
    Cube017_2: THREE.Mesh;
    Cube018_1: THREE.Mesh;
    Cube018_2: THREE.Mesh;
    Cube019_1: THREE.Mesh;
    Cube019_2: THREE.Mesh;
    Cube020_1: THREE.Mesh;
    Cube020_2: THREE.Mesh;
    Cube022_1: THREE.Mesh;
    Cube022_2: THREE.Mesh;
    Cube023_1: THREE.Mesh;
    Cube023_2: THREE.Mesh;
    Cube024: THREE.Mesh;
    Cube024_1: THREE.Mesh;
    Cube015: THREE.Mesh;
    BezierCurve006: THREE.Mesh;
    Cylinder011_1: THREE.Mesh;
    Cylinder011_2: THREE.Mesh;
    BezierCurve007: THREE.Mesh;
    BezierCurve008: THREE.Mesh;
    Icosphere: THREE.Mesh;
    Icosphere001: THREE.Mesh;
    Icosphere002: THREE.Mesh;
    Icosphere003: THREE.Mesh;
    Icosphere004: THREE.Mesh;
    Cylinder004_1: THREE.Mesh;
    Cylinder004_2: THREE.Mesh;
    Cube026: THREE.Mesh;
    Cube027: THREE.Mesh;
    Cube028_1: THREE.Mesh;
    Cube028_2: THREE.Mesh;
    Cube029_1: THREE.Mesh;
    Cube029_2: THREE.Mesh;
    Cube030_1: THREE.Mesh;
    Cube030_2: THREE.Mesh;
    Cylinder008_1: THREE.Mesh;
    Cylinder008_2: THREE.Mesh;
    BezierCurve009: THREE.Mesh;
    Cylinder014: THREE.Mesh;
    Cylinder019: THREE.Mesh;
    Cube031_1: THREE.Mesh;
    Cube031_2: THREE.Mesh;
    Sphere005: THREE.Mesh;
    Sphere006: THREE.Mesh;
    Sphere007: THREE.Mesh;
    Torus: THREE.Mesh;
    Sphere008: THREE.Mesh;
    Cylinder015: THREE.Mesh;
    Plane019: THREE.Mesh;
    Plane020: THREE.Mesh;
    Cube035: THREE.Mesh;
    Cube035_1: THREE.Mesh;
    Plane023: THREE.Mesh;
    Sphere009: THREE.Mesh;
    Cylinder022: THREE.Mesh;
    Cylinder022_1: THREE.Mesh;
    Cylinder022_2: THREE.Mesh;
    Icosphere007: THREE.Mesh;
    Plane028: THREE.Mesh;
    BezierCurve017: THREE.Mesh;
    Cube047: THREE.Mesh;
    Cube053: THREE.Mesh;
    Cube054: THREE.Mesh;
    Cube055: THREE.Mesh;
    Cube056: THREE.Mesh;
    Cylinder023: THREE.Mesh;
    Cylinder019_1: THREE.Mesh;
    Cylinder019_2: THREE.Mesh;
    Cylinder019_3: THREE.Mesh;
    Cylinder025: THREE.Mesh;
    Icosphere006: THREE.Mesh;
    Cylinder020_1: THREE.Mesh;
    Cylinder020_2: THREE.Mesh;
    Cube136: THREE.Mesh;
    Cube136_1: THREE.Mesh;
    Cube136_2: THREE.Mesh;
    Circle011: THREE.Mesh;
    Circle014: THREE.Mesh;
    Circle036: THREE.Mesh;
    Circle039: THREE.Mesh;
    Circle103: THREE.Mesh;
    Cylinder029: THREE.Mesh;
    Cylinder033: THREE.Mesh;
    Circle144: THREE.Mesh;
    Circle150_1: THREE.Mesh;
    Circle150_2: THREE.Mesh;
    Cube005: THREE.Mesh;
    Cube032: THREE.Mesh;
    Cube033: THREE.Mesh;
    Cube154: THREE.Mesh;
    Cube155: THREE.Mesh;
    BezierCurve019: THREE.Mesh;
    Cylinder034: THREE.Mesh;
    Cylinder030_1: THREE.Mesh;
    Cylinder030_2: THREE.Mesh;
    Cylinder036_1: THREE.Mesh;
    Cylinder036_2: THREE.Mesh;
    Cylinder027: THREE.Mesh;
    Cylinder028: THREE.Mesh;
    Cylinder030: THREE.Mesh;
    Cylinder031: THREE.Mesh;
    Cylinder032: THREE.Mesh;
    Cylinder035: THREE.Mesh;
    Cube009_1: THREE.Mesh;
    Cube009_2: THREE.Mesh;
    Icosphere008_1: THREE.Mesh;
    Icosphere008_2: THREE.Mesh;
    Cylinder016: THREE.Mesh;
    Sphere004: THREE.Mesh;
    Sphere010: THREE.Mesh;
    Sphere011: THREE.Mesh;
    Sphere012: THREE.Mesh;
    Sphere013: THREE.Mesh;
    Sphere014: THREE.Mesh;
    Sphere015: THREE.Mesh;
    Sphere016: THREE.Mesh;
    Sphere017: THREE.Mesh;
    Sphere018: THREE.Mesh;
    Sphere019: THREE.Mesh;
    Sphere020: THREE.Mesh;
    Sphere022: THREE.Mesh;
    Sphere021: THREE.Mesh;
    Sphere023: THREE.Mesh;
    Sphere024: THREE.Mesh;
    Sphere025: THREE.Mesh;
    Sphere026: THREE.Mesh;
    Sphere027: THREE.Mesh;
    Sphere028: THREE.Mesh;
    Sphere029: THREE.Mesh;
    Plane022: THREE.Mesh;
    Cylinder036: THREE.Mesh;
    Plane001: THREE.Mesh;
    Icosphere005: THREE.Mesh;
    Cylinder037: THREE.Mesh;
    Cylinder038: THREE.Mesh;
    Cylinder039: THREE.Mesh;
    Cylinder040: THREE.Mesh;
    Cylinder041: THREE.Mesh;
    Cylinder042: THREE.Mesh;
    Cylinder043: THREE.Mesh;
    Cylinder044: THREE.Mesh;
    BezierCurve003: THREE.Mesh;
    Icosphere009: THREE.Mesh;
    Cube001: THREE.Mesh;
    Cylinder045_1: THREE.Mesh;
    Cylinder045_2: THREE.Mesh;
    Cylinder046_1: THREE.Mesh;
    Cylinder046_2: THREE.Mesh;
    Cylinder047: THREE.Mesh;
    Cylinder047_1: THREE.Mesh;
    Cylinder021: THREE.Mesh;
    Cylinder045: THREE.Mesh;
    Cylinder046: THREE.Mesh;
    Sphere030: THREE.Mesh;
    Sphere031: THREE.Mesh;
    Sphere032: THREE.Mesh;
    Plane002: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
    ["Material.004"]: THREE.MeshStandardMaterial;
    ["Material.006"]: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["Material.011"]: THREE.MeshStandardMaterial;
    ["Material.012"]: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    ["Material.008"]: THREE.MeshStandardMaterial;
    ["Material.019"]: THREE.MeshStandardMaterial;
    ["Material.013"]: THREE.MeshStandardMaterial;
    ["Material.007"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["Material.010"]: THREE.MeshStandardMaterial;
    ["Material.009"]: THREE.MeshStandardMaterial;
    ["Material.021"]: THREE.MeshStandardMaterial;
    ["Material.016"]: THREE.MeshStandardMaterial;
    ["Material.015"]: THREE.MeshStandardMaterial;
    ["Material.017"]: THREE.MeshStandardMaterial;
    ["Material.018"]: THREE.MeshStandardMaterial;
    ["Material.005"]: THREE.MeshStandardMaterial;
    ["Material.020"]: THREE.MeshStandardMaterial;
    ["Material.014"]: THREE.MeshStandardMaterial;
    ["Material.023"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function MenuHouse(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("../../models/MenuHouse.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[0.746, -7.08, -0.022]} scale={14.471}>
        <mesh geometry={nodes.Plane_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Plane_2.geometry} material={materials["Material.004"]} />
        <mesh geometry={nodes.Plane_3.geometry} material={materials["Material.006"]} />
      </group>
      <mesh geometry={nodes.Sphere.geometry} material={materials["Material.002"]} position={[0.498, 4.88, -0.022]} rotation={[0, -1.357, 0]} scale={2.158} />
      <mesh geometry={nodes.Sphere001.geometry} material={materials["Material.002"]} position={[0.499, 3.557, 4.536]} rotation={[Math.PI, -1.078, Math.PI]} scale={[0.893, 1.154, 0.893]} />
      <mesh geometry={nodes.Sphere002.geometry} material={materials["Material.002"]} position={[0.522, 1.826, -3.909]} rotation={[0, -0.72, 0]} scale={[0.955, 1.234, 0.955]} />
      <mesh geometry={nodes.Sphere003.geometry} material={materials["Material.002"]} position={[-1.462, 0.883, 2.942]} rotation={[0, -1.529, 0]} scale={[0.748, 0.828, 0.748]} />
      <group position={[0.678, 7.027, -3.494]} scale={0.477}>
        <mesh geometry={nodes.Cube001_1.geometry} material={materials["Material.011"]} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials["Material.012"]} />
      </group>
      <mesh geometry={nodes.BezierCurve.geometry} material={materials["Material.001"]} position={[0.694, 7.006, -3.334]} rotation={[0, 0, Math.PI / 2]} scale={1.746} />
      <mesh geometry={nodes.Cube003.geometry} material={materials["Material.008"]} position={[-1.756, -2.911, -0.603]} rotation={[-2.164, 1.439, 2.104]} scale={[0.02, 0.307, 0.05]} />
      <group position={[-1.001, 0.217, 3.863]} rotation={[0, -0.113, 0]} scale={0.99}>
        <mesh geometry={nodes.BezierCurve005_1.geometry} material={materials["Material.001"]} />
        <mesh geometry={nodes.BezierCurve005_2.geometry} material={materials["Material.019"]} />
      </group>
      <mesh geometry={nodes.BezierCurve004.geometry} material={materials["Material.008"]} position={[1.191, 2.758, 4.185]} rotation={[0.971, 0.379, 0.166]} scale={0.64} />
      <mesh geometry={nodes.Cube009.geometry} material={materials["Material.006"]} position={[0.495, 2.648, 3.808]} rotation={[0.105, 0, 0]} scale={[0.205, 0.026, 0.067]} />
      <group position={[0.411, -2.432, 4.413]} rotation={[0.475, 0.727, -0.33]} scale={[0.039, 0.18, 0.039]}>
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials["Material.013"]} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials["Material.006"]} />
      </group>
      <mesh geometry={nodes.Cylinder001.geometry} material={materials["Material.007"]} position={[0.505, 5.291, 4.54]} scale={[0.048, 0.561, 0.048]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials["Material.007"]} position={[0.523, 2.987, -4.079]} rotation={[-0.261, 0, 0]} scale={[0.273, 0.075, 0.273]} />
      <mesh geometry={nodes.BezierCurve005.geometry} material={materials["Material.001"]} position={[3.274, 4.005, -0.331]} rotation={[-Math.PI, 0.891, -Math.PI]} scale={0.553} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials["Material.003"]} position={[0.918, 6.581, 1.132]} rotation={[0.671, -0.016, -0.248]} scale={[0.265, 0.116, 0.265]} />
      <mesh geometry={nodes.Cylinder007.geometry} material={materials["Material.003"]} position={[1.463, 9.065, 2.78]} rotation={[0.102, -0.095, -0.076]} scale={[0.248, 0.068, 0.248]} />
      <mesh geometry={nodes.Plane005.geometry} material={materials["Material.007"]} position={[-1.035, 6.29, 0.279]} rotation={[-0.053, -0.061, 0.411]} scale={[0.494, 1.022, 1.182]} />
      <mesh geometry={nodes.Plane006.geometry} material={materials["Material.007"]} position={[-0.135, 4.11, 4.877]} rotation={[-0.054, 0.247, 0.427]} scale={[0.313, 0.648, 0.749]} />
      <mesh geometry={nodes.Plane007.geometry} material={materials["Material.007"]} position={[0.474, 3.655, 2.109]} rotation={[-0.206, 1.31, 0.613]} scale={[0.313, 0.648, 0.749]} />
      <mesh geometry={nodes.Plane008.geometry} material={materials["Material.007"]} position={[0.51, 3.493, 3.736]} rotation={[-2.936, -1.31, -2.529]} scale={[0.313, 0.648, 0.749]} />
      <mesh geometry={nodes.Cube012.geometry} material={materials["Material.006"]} position={[0.565, 0.998, -1.977]} rotation={[0.013, -0.003, 0.011]} scale={[0.181, 0.016, 0.042]} />
      <mesh geometry={nodes.Plane009.geometry} material={materials["Material.007"]} position={[0.529, 1.79, -3.046]} rotation={[-0.206, 1.31, 0.613]} scale={[0.246, 0.51, 0.589]} />
      <mesh geometry={nodes.Plane010.geometry} material={materials["Material.007"]} position={[0.575, 1.783, -2.12]} rotation={[-2.936, -1.31, -2.529]} scale={[0.292, 0.605, 0.7]} />
      <group position={[0.518, 3.184, 2.087]} scale={[0.206, 0.412, 0.034]}>
        <mesh geometry={nodes.Cube013_1.geometry} material={materials["Material.006"]} />
        <mesh geometry={nodes.Cube013_2.geometry} material={materials["Material.010"]} />
      </group>
      <mesh geometry={nodes.Plane011.geometry} material={materials["Material.007"]} position={[-0.338, 1.254, -4.237]} rotation={[-0.063, -0.576, 0.38]} scale={[0.268, 0.555, 0.641]} />
      <mesh geometry={nodes.Plane012.geometry} material={materials["Material.007"]} position={[-0.881, 2.325, -1.674]} rotation={[-0.134, -1.165, 0.291]} scale={[0.268, 0.555, 0.641]} />
      <mesh geometry={nodes.Plane013.geometry} material={materials["Material.007"]} position={[-1.925, 1.015, 2.453]} rotation={[-0.11, -1.124, 0.313]} scale={[0.258, 0.482, 0.632]} />
      <mesh geometry={nodes.Plane014.geometry} material={materials["Material.007"]} position={[-2.15, 0.531, 3.108]} rotation={[-0.047, 0.013, 0.413]} scale={[0.186, 0.346, 0.454]} />
      <mesh geometry={nodes.Plane015.geometry} material={materials["Material.007"]} position={[2.327, 4.722, 0.97]} rotation={[-3.069, 0.759, -2.778]} scale={[0.359, 0.743, 0.859]} />
      <mesh geometry={nodes.Plane016.geometry} material={materials["Material.007"]} position={[1.966, 5.88, -1.15]} rotation={[-3.086, -0.353, -2.708]} scale={[0.244, 0.505, 0.584]} />
      <mesh geometry={nodes.Plane017.geometry} material={materials["Material.007"]} position={[0.786, 5.543, -1.973]} rotation={[-3.026, -1.098, -2.625]} scale={[0.357, 0.738, 0.854]} />
      <mesh geometry={nodes.Plane018.geometry} material={materials["Material.007"]} position={[2.538, 2.271, -0.534]} rotation={[-3.089, -0.045, -2.725]} scale={[0.268, 0.555, 0.642]} />
      <group position={[-1.321, 5.515, 0.339]} rotation={[-0.046, 0.163, -0.049]} scale={[0.015, 0.672, 0.337]}>
        <mesh geometry={nodes.Cube014_1.geometry} material={materials["Material.009"]} />
        <mesh geometry={nodes.Cube014_2.geometry} material={materials["Material.010"]} />
      </group>
      <group position={[-0.872, 2.041, -1.653]} rotation={[0, -0.801, 0]} scale={[0.012, 0.253, 0.253]}>
        <mesh geometry={nodes.Cube016_1.geometry} material={materials["Material.009"]} />
        <mesh geometry={nodes.Cube016_2.geometry} material={materials["Material.010"]} />
      </group>
      <group position={[-0.323, 0.977, -4.23]} rotation={[0, -0.434, 0]} scale={[0.011, 0.232, 0.232]}>
        <mesh geometry={nodes.Cube017_1.geometry} material={materials["Material.009"]} />
        <mesh geometry={nodes.Cube017_2.geometry} material={materials["Material.010"]} />
      </group>
      <group position={[-2.166, 0.371, 3.117]} rotation={[0, 0.385, 0]} scale={[0.006, 0.115, 0.134]}>
        <mesh geometry={nodes.Cube018_1.geometry} material={materials["Material.009"]} />
        <mesh geometry={nodes.Cube018_2.geometry} material={materials["Material.010"]} />
      </group>
      <group position={[-1.959, 0.612, 2.409]} rotation={[0, -0.784, 0]} scale={[0.01, 0.358, 0.198]}>
        <mesh geometry={nodes.Cube019_1.geometry} material={materials["Material.009"]} />
        <mesh geometry={nodes.Cube019_2.geometry} material={materials["Material.010"]} />
      </group>
      <group position={[-0.217, 3.801, 4.936]} rotation={[0, 0.624, -0.128]} scale={[0.011, 0.238, 0.238]}>
        <mesh geometry={nodes.Cube020_1.geometry} material={materials["Material.009"]} />
        <mesh geometry={nodes.Cube020_2.geometry} material={materials["Material.010"]} />
      </group>
      <group position={[2.355, 4.341, 0.988]} rotation={[-Math.PI, 0.409, -Math.PI]} scale={[0.012, 0.321, 0.253]}>
        <mesh geometry={nodes.Cube022_1.geometry} material={materials["Material.009"]} />
        <mesh geometry={nodes.Cube022_2.geometry} material={materials["Material.010"]} />
      </group>
      <group position={[2.571, 1.745, -0.57]} rotation={[Math.PI, -0.213, Math.PI]} scale={[0.012, 0.505, 0.214]}>
        <mesh geometry={nodes.Cube023_1.geometry} material={materials["Material.009"]} />
        <mesh geometry={nodes.Cube023_2.geometry} material={materials["Material.010"]} />
      </group>
      <group position={[2.041, 5.63, -1.227]} rotation={[3.135, -0.674, 2.796]} scale={[0.008, 0.223, 0.176]}>
        <mesh geometry={nodes.Cube024.geometry} material={materials["Material.009"]} />
        <mesh geometry={nodes.Cube024_1.geometry} material={materials["Material.010"]} />
      </group>
      <mesh geometry={nodes.Cube015.geometry} material={materials["Material.006"]} position={[2.778, 4.048, 0.043]} rotation={[0, -0.018, 0]} scale={[0.096, 0.014, 0.495]} />
      <mesh geometry={nodes.BezierCurve006.geometry} material={materials["Material.001"]} position={[3.466, 4.047, -0.186]} rotation={[-Math.PI, 0.891, -Math.PI]} scale={0.231} />
      <group position={[3.244, 4.226, 0.045]} scale={[0.15, 0.174, 0.15]}>
        <mesh geometry={nodes.Cylinder011_1.geometry} material={materials["Material.008"]} />
        <mesh geometry={nodes.Cylinder011_2.geometry} material={materials["Material.007"]} />
      </group>
      <mesh geometry={nodes.BezierCurve007.geometry} material={materials["Material.011"]} position={[3.172, 5.186, 0.236]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.221, 0.419, 0.272]} />
      <mesh geometry={nodes.BezierCurve008.geometry} material={materials["Material.013"]} position={[3.12, 5.378, -0.265]} scale={0.2} />
      <mesh geometry={nodes.Icosphere.geometry} material={materials["Material.004"]} position={[3.115, 4.885, 0.345]} scale={0.038} />
      <mesh geometry={nodes.Icosphere001.geometry} material={materials["Material.004"]} position={[3.115, 4.998, 0.054]} scale={0.027} />
      <mesh geometry={nodes.Icosphere002.geometry} material={materials["Material.004"]} position={[3.125, 4.953, -0.238]} scale={0.037} />
      <mesh geometry={nodes.Icosphere003.geometry} material={materials["Material.004"]} position={[3.115, 4.631, -0.094]} scale={0.034} />
      <mesh geometry={nodes.Icosphere004.geometry} material={materials["Material.004"]} position={[3.089, 4.608, 0.217]} scale={0.034} />
      <group position={[1.816, 1.424, -1.658]} rotation={[-Math.PI / 2, 0, -0.724]} scale={[0.226, 0.03, 0.226]}>
        <mesh geometry={nodes.Cylinder004_1.geometry} material={materials["Material.006"]} />
        <mesh geometry={nodes.Cylinder004_2.geometry} material={materials["Material.010"]} />
      </group>
      <mesh geometry={nodes.Cube026.geometry} material={materials["Material.006"]} position={[1.814, 1.419, -1.656]} rotation={[-Math.PI / 2, 0, -0.724]} scale={[0.184, 0.025, 0.025]} />
      <mesh geometry={nodes.Cube027.geometry} material={materials["Material.006"]} position={[1.813, 1.419, -1.655]} rotation={[0, 0.846, -Math.PI / 2]} scale={[0.184, 0.025, 0.025]} />
      <group position={[0.502, 2.998, 3.703]} rotation={[Math.PI, 0, Math.PI]} scale={[0.194, 0.387, 0.032]}>
        <mesh geometry={nodes.Cube028_1.geometry} material={materials["Material.006"]} />
        <mesh geometry={nodes.Cube028_2.geometry} material={materials["Material.010"]} />
      </group>
      <group position={[0.562, 1.362, -2.104]} rotation={[-Math.PI, 0.04, -Math.PI]} scale={[0.194, 0.387, 0.032]}>
        <mesh geometry={nodes.Cube029_1.geometry} material={materials["Material.006"]} />
        <mesh geometry={nodes.Cube029_2.geometry} material={materials["Material.010"]} />
      </group>
      <group position={[0.562, 1.362, -2.988]} scale={[0.194, 0.387, 0.032]}>
        <mesh geometry={nodes.Cube030_1.geometry} material={materials["Material.006"]} />
        <mesh geometry={nodes.Cube030_2.geometry} material={materials["Material.010"]} />
      </group>
      <group position={[0.622, 8.094, -3.838]} rotation={[0.2, 0, 0]} scale={0.429}>
        <mesh geometry={nodes.Cylinder008_1.geometry} material={materials["Material.006"]} />
        <mesh geometry={nodes.Cylinder008_2.geometry} material={materials["Material.021"]} />
      </group>
      <mesh geometry={nodes.BezierCurve009.geometry} material={materials["Material.016"]} position={[0.729, 7.44, -3.628]} rotation={[0, 0, Math.PI / 2]} scale={0.337} />
      <mesh geometry={nodes.Cylinder014.geometry} material={materials["Material.006"]} position={[1.318, -1.369, 1.146]} rotation={[3.138, 0.568, 3.114]} scale={[0.019, 0.138, 0.019]} />
      <mesh geometry={nodes.Cylinder019.geometry} material={materials["Material.009"]} position={[0.604, 7.27, -4.33]} rotation={[0.168, -0.042, -0.193]} scale={[0.018, 0.149, 0.018]} />
      <group position={[0.828, 5.039, -2.064]} rotation={[-3.058, 0.13, 3.131]} scale={[0.194, 0.387, 0.032]}>
        <mesh geometry={nodes.Cube031_1.geometry} material={materials["Material.006"]} />
        <mesh geometry={nodes.Cube031_2.geometry} material={materials["Material.010"]} />
      </group>
      <mesh geometry={nodes.Sphere005.geometry} material={materials["Material.011"]} position={[-1.606, 1.847, 2.856]} rotation={[-0.149, 0.029, 0.133]} scale={[0.081, 0.133, 0.081]} />
      <mesh geometry={nodes.Sphere006.geometry} material={materials["Material.011"]} position={[-1.584, 1.794, 2.986]} rotation={[0.19, -0.042, 0.043]} scale={[0.081, 0.133, 0.081]} />
      <mesh geometry={nodes.Sphere007.geometry} material={materials["Material.011"]} position={[-1.465, 1.924, 2.903]} rotation={[0.146, 0.038, -0.135]} scale={[0.081, 0.133, 0.081]} />
      <mesh geometry={nodes.Torus.geometry} material={materials["Material.013"]} position={[-1.528, 1.713, 2.925]} scale={[0.182, 0.303, 0.182]} />
      <mesh geometry={nodes.Sphere008.geometry} material={materials["Material.011"]} position={[-1.441, 1.745, 2.963]} rotation={[0.146, 0.038, -0.135]} scale={[0.081, 0.133, 0.081]} />
      <mesh geometry={nodes.Cylinder015.geometry} material={materials["Material.008"]} position={[6.074, -3.163, 1.623]} scale={[0.057, 1.256, 0.057]} />
      <mesh geometry={nodes.Plane019.geometry} material={materials["Material.007"]} position={[-0.289, -2.427, 2.652]} rotation={[-0.105, 0.161, 0.797]} scale={[0.297, 1.022, 1.182]} />
      <mesh geometry={nodes.Plane020.geometry} material={materials["Material.007"]} position={[-0.073, -2.503, 1.699]} rotation={[3.037, -0.161, -2.475]} scale={[0.297, 1.022, 1.182]} />
      <group position={[0.228, -3.043, 2.097]} rotation={[3.037, -0.161, 3.076]} scale={[0.028, 0.433, 0.07]}>
        <mesh geometry={nodes.Cube035.geometry} material={materials["Material.008"]} />
        <mesh geometry={nodes.Cube035_1.geometry} material={materials["Material.010"]} />
      </group>
      <mesh geometry={nodes.Plane023.geometry} material={materials["Material.007"]} position={[2.038, -1.899, -2.467]} rotation={[2.779, -0.302, -3.011]} scale={[0.725, 1.022, 1.182]} />
      <mesh geometry={nodes.Sphere009.geometry} material={nodes.Sphere009.material} position={[-1.531, 1.639, 2.929]} rotation={[0.008, -0.024, 0.013]} scale={[0.183, 0.045, 0.183]} />
      <mesh geometry={nodes.Cylinder022.geometry} material={materials["Material.008"]} position={[3.979, -3.4, -3.096]} rotation={[1.362, -0.328, -0.033]} scale={[0.04, 0.147, 0.04]} />
      <group position={[4.328, -4.017, -3.687]} rotation={[-0.337, 0.03, -0.293]} scale={0.118}>
        <mesh geometry={nodes.Cylinder022_1.geometry} material={materials["Material.008"]} />
        <mesh geometry={nodes.Cylinder022_2.geometry} material={materials["Material.001"]} />
      </group>
      <mesh geometry={nodes.Icosphere007.geometry} material={materials["Material.003"]} position={[4.644, -3.684, -1.639]} rotation={[0.562, 0.938, -0.57]} scale={[0.083, 0.065, 0.145]} />
      <mesh geometry={nodes.Plane028.geometry} material={materials["Material.007"]} position={[-3.525, -3.896, -4.715]} rotation={[2.706, -0.282, -2.638]} scale={[0.297, 1.022, 1.182]} />
      <mesh geometry={nodes.BezierCurve017.geometry} material={materials["Material.008"]} position={[-3.781, -4.256, -5.064]} rotation={[-2.266, -0.285, 2.383]} scale={0.429} />
      <mesh geometry={nodes.Cube047.geometry} material={nodes.Cube047.material} position={[-2.062, -3.456, -2.118]} rotation={[-0.008, 0.065, 0.084]} scale={[0.041, 0.088, 0.088]} />
      <mesh geometry={nodes.Cube053.geometry} material={nodes.Cube053.material} position={[-2.551, -3.426, -0.49]} rotation={[-0.006, 0.093, 0.178]} scale={0.088} />
      <mesh geometry={nodes.Cube054.geometry} material={nodes.Cube054.material} position={[-2.342, -3.387, -0.483]} rotation={[-0.006, 0.093, 0.178]} scale={[0.041, 0.088, 0.088]} />
      <mesh geometry={nodes.Cube055.geometry} material={nodes.Cube055.material} position={[-2.108, -3.326, -0.537]} rotation={[-0.006, 0.093, 0.178]} scale={0.088} />
      <mesh geometry={nodes.Cube056.geometry} material={nodes.Cube056.material} position={[-1.899, -3.288, -0.53]} rotation={[-0.006, 0.093, 0.178]} scale={[0.041, 0.088, 0.088]} />
      <mesh geometry={nodes.Cylinder023.geometry} material={materials["Material.015"]} position={[-4.485, -3.888, -1.352]} rotation={[0.005, 0.002, 0.036]} scale={[0.226, 0.024, 0.226]} />
      <group position={[-6.834, -4.836, -3.256]} rotation={[-0.146, -0.037, 0.383]} scale={[0.521, 0.298, 0.521]}>
        <mesh geometry={nodes.Cylinder019_1.geometry} material={materials["Material.017"]} />
        <mesh geometry={nodes.Cylinder019_2.geometry} material={materials["Material.018"]} />
        <mesh geometry={nodes.Cylinder019_3.geometry} material={materials["Material.007"]} />
      </group>
      <mesh geometry={nodes.Cylinder025.geometry} material={materials["Material.005"]} position={[-4.021, -4.16, 1.791]} rotation={[-3.024, -0.043, -0.38]} scale={[0.082, 0.258, 0.082]} />
      <mesh geometry={nodes.Icosphere006.geometry} material={materials["Material.006"]} position={[-3.529, -4.051, 3.091]} rotation={[-0.11, 0.755, 0.451]} scale={[0.039, 0.284, 0.107]} />
      <group position={[4.376, -3.817, -3.83]} rotation={[-1.644, 0.53, -0.06]} scale={[0.017, 0.164, 0.017]}>
        <mesh geometry={nodes.Cylinder020_1.geometry} material={materials["Material.006"]} />
        <mesh geometry={nodes.Cylinder020_2.geometry} material={materials["Material.003"]} />
      </group>
      <group position={[-3.616, -3.122, -1.031]} scale={0.134}>
        <mesh geometry={nodes.Cube136.geometry} material={materials["Material.008"]} />
        <mesh geometry={nodes.Cube136_1.geometry} material={materials["Material.010"]} />
        <mesh geometry={nodes.Cube136_2.geometry} material={materials["Material.016"]} />
      </group>
      <mesh geometry={nodes.Circle011.geometry} material={materials["Material.005"]} position={[-2, -3.319, -2.007]} rotation={[-2.617, 0.982, 0.865]} scale={[0.11, 0.042, 0.014]} />
      <mesh geometry={nodes.Circle014.geometry} material={materials["Material.005"]} position={[-1.827, -3.282, -1.975]} rotation={[-2.617, 0.982, 0.865]} scale={[0.11, 0.042, 0.014]} />
      <mesh geometry={nodes.Circle036.geometry} material={materials["Material.005"]} position={[1.257, -3.39, -3.237]} rotation={[-0.394, 0.446, -1.541]} scale={[0.071, 0.027, 0.009]} />
      <mesh geometry={nodes.Circle039.geometry} material={materials["Material.005"]} position={[1.232, -3.368, -3.125]} rotation={[-0.394, 0.446, -1.541]} scale={[0.071, 0.027, 0.009]} />
      <mesh geometry={nodes.Circle103.geometry} material={materials["Material.005"]} position={[-1.201, -3.201, -3.006]} rotation={[-0.232, 0.473, -1.425]} scale={[0.084, 0.033, 0.011]} />
      <mesh geometry={nodes.Cylinder029.geometry} material={materials["Material.008"]} position={[0.77, 1.103, -2.806]} rotation={[0.09, -0.058, -0.261]} scale={[0.023, 0.184, 0.023]} />
      <mesh geometry={nodes.Cylinder033.geometry} material={materials["Material.006"]} position={[0.615, 0.477, 4.623]} scale={[0.022, 1.579, 0.022]} />
      <mesh geometry={nodes.Circle144.geometry} material={materials["Material.005"]} position={[1.336, -3.352, -3.512]} rotation={[-0.43, -0.497, -1.718]} scale={[0.074, 0.029, 0.01]} />
      <group position={[2.161, -3.491, -3.942]} rotation={[-0.747, -1.191, -2.198]} scale={[0.052, 0.02, 0.007]}>
        <mesh geometry={nodes.Circle150_1.geometry} material={materials["Material.005"]} />
        <mesh geometry={nodes.Circle150_2.geometry} material={materials["Material.020"]} />
      </group>
      <mesh geometry={nodes.Cube005.geometry} material={materials["Material.001"]} position={[0.643, 5.27, -2.978]} rotation={[-0.57, 0, 0]} scale={[0.092, 0.068, 0.092]} />
      <mesh geometry={nodes.Cube032.geometry} material={materials["Material.001"]} position={[0.622, 5.582, -3.138]} rotation={[-0.431, -0.011, -0.005]} scale={[0.092, 0.068, 0.092]} />
      <mesh geometry={nodes.Cube033.geometry} material={materials["Material.001"]} position={[0.602, 5.957, -3.274]} rotation={[-0.28, -0.011, -0.003]} scale={[0.092, 0.068, 0.092]} />
      <mesh geometry={nodes.Cube154.geometry} material={materials["Material.001"]} position={[0.591, 6.323, -3.401]} rotation={[-0.28, -0.011, -0.003]} scale={[0.083, 0.068, 0.092]} />
      <mesh geometry={nodes.Cube155.geometry} material={materials["Material.001"]} position={[0.612, 6.687, -3.488]} rotation={[-0.28, -0.011, -0.003]} scale={[0.077, 0.068, 0.092]} />
      <mesh geometry={nodes.BezierCurve019.geometry} material={materials["Material.003"]} position={[0.702, -2.04, -4.13]} rotation={[Math.PI / 2, 0, 0]} scale={0.148} />
      <mesh geometry={nodes.Cylinder034.geometry} material={materials["Material.009"]} position={[0.713, -1.2, -4.128]} scale={[0.01, 0.639, 0.01]} />
      <group position={[2.973, 4.226, -0.157]} scale={[0.15, 0.174, 0.15]}>
        <mesh geometry={nodes.Cylinder030_1.geometry} material={materials["Material.008"]} />
        <mesh geometry={nodes.Cylinder030_2.geometry} material={materials["Material.007"]} />
      </group>
      <group position={[2.973, 4.226, 0.244]} scale={[0.15, 0.174, 0.15]}>
        <mesh geometry={nodes.Cylinder036_1.geometry} material={materials["Material.008"]} />
        <mesh geometry={nodes.Cylinder036_2.geometry} material={materials["Material.007"]} />
      </group>
      <mesh geometry={nodes.Cylinder027.geometry} material={materials["Material.013"]} position={[0.388, -2.082, -2.746]} scale={0.017} />
      <mesh geometry={nodes.Cylinder028.geometry} material={materials["Material.013"]} position={[0.336, -1.83, -2.998]} scale={0.022} />
      <mesh geometry={nodes.Cylinder030.geometry} material={materials["Material.013"]} position={[2.601, -2.344, 0.316]} rotation={[-Math.PI, 1.286, -Math.PI]} scale={0.022} />
      <mesh geometry={nodes.Cylinder031.geometry} material={materials["Material.013"]} position={[2.847, -2.601, 0.346]} rotation={[0, 1.011, 0]} scale={0.016} />
      <mesh geometry={nodes.Cylinder032.geometry} material={materials["Material.013"]} position={[-0.092, -2.352, 2.38]} rotation={[3.016, 1.28, -2.684]} scale={0.022} />
      <mesh geometry={nodes.Cylinder035.geometry} material={materials["Material.013"]} position={[-1.514, -2.325, 0.909]} rotation={[0.464, -0.018, 0.283]} scale={0.022} />
      <group position={[-2.881, -3.101, -1.841]} rotation={[-0.069, 0.058, 0.112]} scale={[0.005, 0.089, 0.097]}>
        <mesh geometry={nodes.Cube009_1.geometry} material={materials["Material.010"]} />
        <mesh geometry={nodes.Cube009_2.geometry} material={materials["Material.008"]} />
      </group>
      <group position={[-3.947, -3.878, -5.205]} rotation={[2.854, -0.298, 2.835]} scale={0.146}>
        <mesh geometry={nodes.Icosphere008_1.geometry} material={materials["Material.011"]} />
        <mesh geometry={nodes.Icosphere008_2.geometry} material={materials["Material.009"]} />
      </group>
      <mesh geometry={nodes.Cylinder016.geometry} material={materials["Material.008"]} position={[3.625, -4.37, -4.995]} rotation={[0.002, -0.761, 1.654]} scale={[0.043, 0.721, 0.043]} />
      <mesh geometry={nodes.Sphere004.geometry} material={materials["Material.002"]} position={[3.399, -4.508, -5.515]} rotation={[-0.299, 0.014, -0.319]} scale={[0.048, 0.097, 0.02]} />
      <mesh geometry={nodes.Sphere010.geometry} material={materials["Material.002"]} position={[3.434, -4.49, -5.468]} rotation={[-0.299, 0.014, -0.319]} scale={[0.048, 0.097, 0.02]} />
      <mesh geometry={nodes.Sphere011.geometry} material={materials["Material.002"]} position={[3.579, -4.631, -5.681]} rotation={[-0.299, 0.014, -0.319]} scale={[0.048, 0.097, 0.02]} />
      <mesh geometry={nodes.Sphere012.geometry} material={materials["Material.002"]} position={[3.614, -4.612, -5.634]} rotation={[-0.299, 0.014, -0.319]} scale={[0.048, 0.097, 0.02]} />
      <mesh geometry={nodes.Sphere013.geometry} material={materials["Material.002"]} position={[3.666, -4.553, -5.52]} rotation={[-0.397, 0.006, -0.184]} scale={[0.055, 0.111, 0.023]} />
      <mesh geometry={nodes.Sphere014.geometry} material={materials["Material.002"]} position={[3.705, -4.522, -5.47]} rotation={[-0.397, 0.006, -0.184]} scale={[0.055, 0.111, 0.023]} />
      <mesh geometry={nodes.Sphere015.geometry} material={materials["Material.005"]} position={[3.722, -4.482, -5.253]} scale={0.032} />
      <mesh geometry={nodes.Sphere016.geometry} material={materials["Material.005"]} position={[3.686, -4.49, -5.286]} scale={0.019} />
      <mesh geometry={nodes.Sphere017.geometry} material={materials["Material.005"]} position={[3.814, -4.54, -5.338]} scale={0.032} />
      <mesh geometry={nodes.Sphere018.geometry} material={materials["Material.005"]} position={[3.772, -4.529, -5.34]} scale={0.024} />
      <mesh geometry={nodes.Sphere019.geometry} material={materials["Material.005"]} position={[3.925, -4.603, -5.432]} scale={0.032} />
      <mesh geometry={nodes.Sphere020.geometry} material={materials["Material.005"]} position={[3.922, -4.625, -5.47]} scale={0.04} />
      <mesh geometry={nodes.Sphere022.geometry} material={materials["Material.002"]} position={[4.056, -4.371, -4.772]} rotation={[-0.031, 0.704, -0.38]} scale={[0.025, 0.077, 0.016]} />
      <mesh geometry={nodes.Sphere021.geometry} material={materials["Material.002"]} position={[4.187, -4.443, -4.881]} rotation={[1.329, 1.284, -1.611]} scale={[0.035, 0.11, 0.023]} />
      <mesh geometry={nodes.Sphere023.geometry} material={materials["Material.002"]} position={[4.321, -4.517, -4.993]} rotation={[-0.031, 0.704, -0.38]} scale={[0.03, 0.093, 0.02]} />
      <mesh geometry={nodes.Sphere024.geometry} material={materials["Material.012"]} position={[3.929, -4.451, -5.027]} scale={0.07} />
      <mesh geometry={nodes.Sphere025.geometry} material={materials["Material.012"]} position={[3.87, -4.466, -5.094]} scale={0.033} />
      <mesh geometry={nodes.Sphere026.geometry} material={materials["Material.012"]} position={[3.942, -4.49, -5.111]} scale={0.042} />
      <mesh geometry={nodes.Sphere027.geometry} material={materials["Material.012"]} position={[4.1, -4.572, -5.175]} scale={0.056} />
      <mesh geometry={nodes.Sphere028.geometry} material={materials["Material.012"]} position={[4.039, -4.586, -5.232]} scale={0.033} />
      <mesh geometry={nodes.Sphere029.geometry} material={materials["Material.012"]} position={[4.11, -4.602, -5.242]} scale={0.033} />
      <mesh geometry={nodes.Plane022.geometry} material={materials["Material.014"]} position={[3.857, -4.526, -5.251]} rotation={[-0.143, 0.808, -0.323]} scale={[0.374, 1, 0.724]} />
      <mesh geometry={nodes.Cylinder036.geometry} material={materials["Material.008"]} position={[10.61, -5.873, 3.522]} rotation={[Math.PI, -0.029, Math.PI]} scale={[0.057, 1.256, 0.057]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials["Material.023"]} position={[0.993, -10.436, -1.272]} scale={851.994} />
      <mesh geometry={nodes.Icosphere005.geometry} material={nodes.Icosphere005.material} position={[4.008, -4.523, -14.714]} scale={[0.014, 0.134, 0.044]} />
      <mesh geometry={nodes.Cylinder037.geometry} material={materials["Material.005"]} position={[-4.125, -4.169, 1.58]} rotation={[0.187, -0.131, -2.758]} scale={[0.104, 0.329, 0.104]} />
      <mesh geometry={nodes.Cylinder038.geometry} material={materials["Material.005"]} position={[-3.946, -4.113, 1.632]} rotation={[0.187, -0.131, -2.758]} scale={[0.062, 0.196, 0.062]} />
      <mesh geometry={nodes.Cylinder039.geometry} material={materials["Material.005"]} position={[-4.48, -4.405, 2.176]} rotation={[0.285, -0.359, -2.734]} scale={[0.082, 0.258, 0.082]} />
      <mesh geometry={nodes.Cylinder040.geometry} material={materials["Material.005"]} position={[-4.469, -4.428, 2.41]} rotation={[-2.771, 0.53, -0.444]} scale={[0.104, 0.329, 0.104]} />
      <mesh geometry={nodes.Cylinder041.geometry} material={materials["Material.005"]} position={[-4.609, -4.476, 2.283]} rotation={[-2.771, 0.53, -0.444]} scale={[0.062, 0.196, 0.062]} />
      <mesh geometry={nodes.Cylinder042.geometry} material={materials["Material.005"]} position={[-4.619, -4.361, 1.642]} rotation={[-2.771, 0.53, -0.444]} scale={[0.11, 0.348, 0.11]} />
      <mesh geometry={nodes.Cylinder043.geometry} material={materials["Material.005"]} position={[-3.912, -3.995, 0.992]} rotation={[-2.771, 0.53, -0.444]} scale={[0.073, 0.229, 0.073]} />
      <mesh geometry={nodes.Cylinder044.geometry} material={materials["Material.005"]} position={[-3.992, -4.078, 1.508]} rotation={[-2.297, 1.021, -0.789]} scale={[0.051, 0.16, 0.051]} />
      <mesh geometry={nodes.BezierCurve003.geometry} material={materials["Material.003"]} position={[10.765, -4.535, 3.49]} />
      <mesh geometry={nodes.Icosphere009.geometry} material={materials["Material.009"]} position={[4.726, -3.782, -1.867]} rotation={[-0.208, -0.028, -0.359]} scale={[0.281, 0.037, 0.281]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials["Material.012"]} position={[0.278, 5.556, 4.829]} scale={[0.209, 0.289, 0.289]} />
      <group position={[4.789, -3.86, -2.643]} rotation={[-0.221, 0.054, -0.334]} scale={[0.147, 0.125, 0.147]}>
        <mesh geometry={nodes.Cylinder045_1.geometry} material={materials["Material.008"]} />
        <mesh geometry={nodes.Cylinder045_2.geometry} material={materials["Material.001"]} />
      </group>
      <group position={[5.363, -3.828, -1.214]} rotation={[-0.147, 0.067, -0.362]} scale={[0.147, 0.125, 0.147]}>
        <mesh geometry={nodes.Cylinder046_1.geometry} material={materials["Material.008"]} />
        <mesh geometry={nodes.Cylinder046_2.geometry} material={materials["Material.001"]} />
      </group>
      <group position={[4.187, -3.343, -0.629]} rotation={[-0.131, 0.08, -0.338]} scale={[0.147, 0.125, 0.147]}>
        <mesh geometry={nodes.Cylinder047.geometry} material={materials["Material.008"]} />
        <mesh geometry={nodes.Cylinder047_1.geometry} material={materials["Material.001"]} />
      </group>
      <mesh geometry={nodes.Cylinder021.geometry} material={materials["Material.008"]} position={[4.778, -3.784, -1.97]} rotation={[1.728, 0.637, -0.504]} scale={0.029} />
      <mesh geometry={nodes.Cylinder045.geometry} material={materials["Material.008"]} position={[4.64, -3.743, -1.921]} rotation={[2.341, 0.468, -1.207]} scale={0.029} />
      <mesh geometry={nodes.Cylinder046.geometry} material={materials["Material.008"]} position={[4.612, -3.719, -1.851]} rotation={[2.341, 0.468, -1.207]} scale={0.029} />
      <mesh geometry={nodes.Sphere030.geometry} material={materials["Material.002"]} position={[4.4, -4.587, -5.07]} rotation={[-0.031, 0.704, -0.38]} scale={[0.02, 0.062, 0.013]} />
      <mesh geometry={nodes.Sphere031.geometry} material={materials["Material.005"]} position={[3.643, -4.436, -5.223]} rotation={[1.845, 0.529, -2]} scale={0.032} />
      <mesh geometry={nodes.Sphere032.geometry} material={materials["Material.005"]} position={[3.632, -4.414, -5.18]} rotation={[1.845, 0.529, -2]} scale={0.019} />
      <mesh geometry={nodes.Plane002.geometry} material={materials["Material.015"]} position={[-3.525, -3.896, -4.715]} rotation={[2.706, -0.282, -2.638]} scale={[0.297, 1.022, 1.182]} />
    </group>
  );
}

useGLTF.preload("../../models/MenuHouse.glb");
